import java.util.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

public class AutoTyper {
    public static void main(String[] args) throws AWTException, InterruptedException {
        System.out.println("Activated.......................");
        Thread.sleep(5000);

        List<String> birds = Arrays.asList("African Grey Parrot", "American Robin", "Andean Condor", "Bald Eagle",
                "Barn Owl", "Barred Owl", "Black-capped Chickadee", "Blue Jay", "Bufflehead", "California Condor",
                "Canada Goose", "Carolina Wren", "Common Blackbird", "Common Buzzard", "Common Eider",
                "Common Gallinule", "Common Goldeneye", "Common Grackle", "Common Kingfisher", "Common Myna",
                "Common Redpoll", "Common Starling", "Common Swift", "Crowned Crane", "European Goldfinch",
                "European Greenfinch", "European Robin", "Eurasian Collared-Dove", "Eurasian Nuthatch", "Finch",
                "Flamingo", "Gadwall", "Gyrfalcon", "Hooded Merganser", "House Sparrow", "Indian Peafowl",
                "Indigo Bunting", "Ibis", "Kestrel", "King Vulture", "Kookaburra", "Lazuli Bunting", "Lesser Scaup",
                "Magpie", "Mallard", "Mandarin Duck", "Northern Cardinal", "Northern Flicker", "Northern Mockingbird",
                "Osprey", "Ostrich", "Owlet", "Peregrine Falcon", "Pigeon", "Pintail", "Red-shouldered Hawk",
                "Red-tailed Hawk", "Robin", "Rock Pigeon", "Roseate Spoonbill", "Ruff", "Sandhill Crane",
                "Scarlet Macaw", "Secretary Bird", "Snowy Owl", "Song Sparrow", "Sora", "Spotted Sandpiper",
                "Spoonbill", "Steller's Jay", "Swallow", "Swift", "Tawny Owl", "Tree Sparrow", "Tropicbird",
                "Turkey Vulture", "Vermilion Flycatcher", "White-breasted Nuthatch", "Wood Duck", "Yellow Warbler",
                "Yellow-bellied Sapsucker", "Zebra Finch", "Abyssinian Ground Hornbill", "Albatross",
                "African Fish Eagle", "American Bittern", "American Coot", "American Oystercatcher", "Antbird",
                "Avocet", "Bald Eagle", "Black Marabou", "Black-throated Blue Warbler", "Blue-footed Booby",
                "Bridled Tern", "Buff-breasted Sandpiper", "California Quail", "Capercaillie", "Cassowary", "Chaffinch",
                "Chickadee", "Chough", "Cockatoo", "Common Loon", "Crowned Pigeon", "Cuckoo", "Cyanocitta",
                "Dartford Warbler", "Dickcissel", "Double-crested Cormorant", "Dove", "Dunlin", "Eastern Bluebird",
                "Eastern Kingbird", "Eastern Towhee", "Eurasian Blue Tit", "European Bee-eater",
                "European Green Woodpecker", "European Magpie", "European Nightjar", "Feral Pigeon",
                "Flame-colored Tanager", "Greater Scaup", "Green Jay", "Grey Heron", "Grey Partridge", "Hawaiian Goose",
                "Herring Gull", "Hooded Crow", "House Finch", "Hummingbird", "Indian Grey Hornbill", "Indian Roller",
                "Iridescent Crow", "Jackdaw", "Javan Hawk-Eagle", "Jay", "Junco", "Kea", "Kookaburra",
                "Lesser Golden Pheasant", "Little Egret", "Little Grebe", "Long-tailed Tit", "Magnolia Warbler",
                "Malayan Hornbill", "Mandarin Duck", "Marabou Stork", "Masked Booby", "Mourning Dove", "Muscovy Duck",
                "Nandu", "Nighthawk", "Northern Bobwhite", "Olive-sided Flycatcher", "Orange-crowned Warbler",
                "Ovenbird", "Pacific Black Duck", "Pallas's Fish Eagle", "Pheasant", "Pied Avocet", "Pigeon", "Pintail",
                "Plover", "Purple Martin", "Purple Swamphen", "Red Bishop", "Red-headed Woodpecker",
                "Red-winged Blackbird", "Ruffed Grouse", "Sandpiper", "Satin Bowerbird", "Sedge Warbler", "Serin",
                "Shorebird", "Silver Gull", "Siskin", "Skua", "Slate-colored Junco", "Spoon-billed Sandpiper",
                "Starling", "Stork", "Superb Lyrebird", "Surfbird", "Swallow-tailed Kite", "Teal", "Tern",
                "Turtle Dove", "Vulture", "Wader", "Wandering Albatross", "Warbler", "Western Bluebird",
                "Western Meadowlark", "Whip-poor-will", "White-bellied Sea Eagle", "White-tailed Eagle", "Woodcock",
                "Woodpecker", "Yellow-headed Blackbird", "Yellowthroat", "African Grey Hornbill", "Bornean Bristlehead",
                "Ceylon Frogmouth", "Cockatiel", "Collared Dove", "Common Goldeneye", "Corncrake", "Crane",
                "Dusky Thrush", "Eurasian Wren", "Flamingo", "Giant Ibis", "Great Egret",
                "Great Blue Heron", "Great Horned Owl", "Green Heron", "Guianan Cock-of-the-rock", "Hooded Pitohui",
                "Horned Puffin", "Indian Blue Robin", "Iriomote Cat", "Java Sparrow", "Long-billed Curlew",
                "Malleefowl", "Myna", "Nandu", "New Zealand Kiwi", "Piping Plover", "Plumbeous Kite", "Purple Swamphen",
                "Red-footed Booby", "Red-throated Diver", "Ruby-throated Hummingbird", "Saddle-billed Stork",
                "Sarus Crane", "Snow Goose", "Spectacled Eider", "Tawny Frogmouth", "Trumpeter Swan",
                "Vulturine Guineafowl", "Wandering Tattler", "Western Red-tailed Hawk", "Yellow-crowned Night Heron",
                "Yellow-eyed Penguin", "Yellow-tailed Black Cockatoo", "Zebra Dove", "Zitting Cisticola",
                "African Blue Flycatcher", "Akanthizidae", "Alca", "Amazon Kingfisher", "American Redstart",
                "American Tree Sparrow", "Amethyst Sunbird", "Antpitta", "Antthrush", "Apapane", "Arctic Tern",
                "Asian Paradise Flycatcher", "Australian Brush-turkey", "Australian King-Parrot", "Banded Palm Civet",
                "Barnacle Goose", "Barred Antshrike", "Barred Hawk", "Bennett's Wallaby", "Bishop",
                "Black-shouldered Kite", "Brambling", "Buff-bellied Hummingbird", "Buffons Macaw", "California Thrush",
                "Canary", "Cape Verde Warbler", "Capuchinbird", "Caracara", "Caribbean Flamingo", "Cassowary",
                "Cattle Egret", "Cedar Waxwing", "Chestnut-sided Warbler", "Chickadee", "Chimney Swift",
                "Chinese Pond Heron", "Cinnamon Teal", "Cliff Swallow", "Cloud-Cuckoo", "Common Chiffchaff",
                "Common House Martin", "Common Moorhen", "Common Nightingale", "Common Redstart", "Common Sandpiper",
                "Common Stonechat", "Common Yellowthroat", "Crowned Woodnymph", "Cuckoo-Shrike", "Dabchick",
                "Dartmoor Mare", "Dove", "Eastern Chiffchaff", "Eastern Whip-poor-will", "Eastern Wood-Pewee",
                "Eurasian Blue Tit", "Eurasian Collared-Dove", "Eurasian Spoonbill", "Eurasian Tree Sparrow",
                "European Turtle Dove", "Finch", "Flamebird", "Flattish", "Flycatcher", "Forest Owlet", "Fulmar",
                "Gadwall", "Gerygone", "Goldeneye", "Goshawk", "Greater Flamingo", "Green Bee-eater", "Grey Catbird",
                "Grey Jay", "Grey Wagtail", "Gull-billed Tern", "Hairy Woodpecker", "Hawaiian Honeycreeper",
                "Himalayan Monal", "Hooded Crow", "House Wren", "Imperial Moth", "Indian Hill Myna", "Indian Pitta",
                "Ivory Gull", "Jacana", "Kagu", "Kookaburra", "Lappet-faced Vulture", "Least Bittern", "Least Tern",
                "Long-legged Buzzard", "Long-tailed Duck", "Macaroni Penguin", "Magnolia Warbler", "Marabou",
                "Masked Trogon", "Mew Gull", "Moorhen", "Mynah", "Neotropic Cormorant", "Nuthatch", "Olive Warbler",
                "Orange-breasted Bunting", "Ostrich", "Ovenbird", "Pacific Black Duck", "Pale Thrush", "Pale-vented");
        List<String> animals = Arrays.asList("Aardvark", "Abyssinian", "African Bullfrog", "African Grey Parrot",
                "Albatross", "Alligator", "Alpaca", "Amur Leopard", "Anaconda", "Ant", "Antelope", "Armadillo",
                "Asian Elephant", "Aurochs", "Axolotl", "Bactrian Camel", "Badger", "Baiji", "Banded Palm Civet",
                "Barb", "Basilisk", "Binturong", "Bison", "Bongo", "Bonito", "Bongo Cat", "Book Louse", "Bongo Dolphin",
                "Bongo Frog", "Booby", "Bobcat", "Bongo Antelope", "Bonito Fish", "Bongo Octopus", "Bongo Shark",
                "Bongo Whale", "Bongo Bat", "Bongo Giraffe", "Bongo Lion", "Bongo Elephant", "Bongo Penguin",
                "Bongo Fox", "Bongo Lizard", "Bongo Toad", "Bongo Owl", "Bongo Cheetah", "Bongo Parrot", "Bongo Monkey",
                "Bongo Wallaby", "Bongo Vulture", "Bongo Lemur", "Bongo Tortoise", "Bongo Manatee", "Bongo Seahorse",
                "Bongo Starfish", "Bongo Wombat", "Bongo Sloth", "Bongo Shark", "Bongo Salamander", "Bongo Cuttlefish",
                "Bongo Lobster", "Bongo Narwhal", "Bongo Tarantula", "Bongo Ant", "Bongo Fly", "Bongo Beetle",
                "Bongo Butterfly", "Bongo Moth", "Bongo Caterpillar", "Bongo Snail", "Bongo Worm", "Bongo Jellyfish",
                "Bongo Sea Urchin", "Bongo Crab", "Bongo Scorpion", "Bongo Shrimp", "Bongo Clam", "Bongo Octopus",
                "Bongo Squid", "Bongo Prawn", "Bongo Eel", "Bongo Lobster", "Bongo Starfish", "Bongo Sea Cucumber",
                "Bongo Anemone", "Bongo Coral", "Bongo Sea Horse", "Bongo Clownfish", "Bongo Angelfish", "Bongo Betta",
                "Bongo Guppy", "Bongo Goldfish", "Bongo Koi", "Bongo Cichlid", "Bongo Piranha", "Bongo Archerfish",
                "Bongo Surgeonfish", "Bongo Parrotfish", "Bongo Butterflyfish", "Bongo Wrasse", "Bongo Snapper",
                "Bongo Grouper", "Bongo Mackerel", "Bongo Barracuda", "Bongo Tuna", "Bongo Marlin", "Bongo Swordfish",
                "Bongo Sailfish", "Bongo Triggerfish", "Bongo Boxfish", "Bongo Scad", "Bongo Garfish", "Bongo Carp",
                "Bongo Catfish", "Bongo Ray", "Bongo Shark", "Bongo Sturgeon", "Bongo Manta Ray", "Bongo Sunfish",
                "Bongo Electric Eel", "Bongo Arowana", "Bongo Betta", "Bongo Mantis Shrimp", "Bongo Sea Turtle",
                "Bongo Manatee", "Bongo Dugong", "Bongo Sea Lion", "Bongo Walrus", "Bongo Sea Otter", "Bongo Dolphin",
                "Bongo Whale", "Bongo Shark", "Bongo Stingray", "Bongo Crab", "Bongo Lobster", "Bongo Scallop",
                "Bongo Oyster", "Bongo Clam", "Bongo Conch", "Bongo Sea Snail", "Bongo Sea Slug", "Bongo Jellyfish",
                "Bongo Anemone", "Bongo Coral", "Bongo Urchin", "Bongo Sea Cucumber", "Bongo Sponge", "Bongo Starfish",
                "Bongo Brine Shrimp", "Bongo Daphnia", "Bongo Copepod", "Bongo Barnacle", "Bongo Mysid", "Bongo Krill",
                "Bongo Amphipod", "Bongo Flatworm", "Bongo Roundworm", "Bongo Nematode", "Bongo Earthworm",
                "Bongo Leech", "Bongo Spongillidae", "Bongo Porifera", "Bongo Cnidaria", "Bongo Echinoderm",
                "Bongo Mollusca",
                "Bongo Arthropoda", "Bongo Annelida", "Bongo Chordata", "Bongo Hemichordata", "Bongo Urochordata",
                "Bongo Lancelet", "Bongo Vertebrate", "Bongo Invertebrate", "Bongo Fish", "Bongo Amphibian",
                "Bongo Reptile", "Bongo Bird", "Bongo Mammal", "Bongo Aves", "Bongo Mammalia", "Bongo Insecta",
                "Bongo Arachnida", "Bongo Crustacea", "Bongo Myriapoda", "Bongo Chilopoda", "Bongo Diplopoda",
                "Bongo Symphyla", "Bongo Pauropoda", "Bongo Tardigrada", "Bongo Onychophora", "Bongo Kinorhyncha",
                "Bongo Priapulida", "Bongo Nematoda", "Bongo Nemertea", "Bongo Platyhelminthes", "Bongo Cnidaria",
                "Bongo Porifera", "Bongo Ctenophora", "Bongo Echinoidea", "Bongo Asteroidea", "Bongo Ophiuroidea",
                "Bongo Holothuroidea", "Bongo Crinoidea", "Bongo Polychaeta", "Bongo Oligochaeta", "Bongo Hirudinea",
                "Bongo Gastropoda", "Bongo Bivalvia", "Bongo Cephalopoda", "Bongo Scaphopoda", "Bongo Polyplacophora",
                "Bongo Monoplacophora", "Bongo Caudofoveata", "Bongo Aplacophora", "Bongo Echinodermata",
                "Bongo Hemichordata", "Bongo Urochordata", "Bongo Tunicata", "Bongo Ascidiacea", "Bongo Thaliacea",
                "Bongo Appendicularia", "Bongo Craniata", "Bongo Myxini", "Bongo Petromyzontida",
                "Bongo Chondrichthyes", "Bongo Actinopterygii", "Bongo Sarcopterygii", "Bongo Amphibia",
                "Bongo Reptilia", "Bongo Aves", "Bongo Mammalia", "Bongo Amniota", "Bongo Mammalia", "Bongo Insecta",
                "Bongo Arachnida", "Bongo Crustacea", "Bongo Myriapoda", "Bongo Hexapoda", "Bongo Coelenterata",
                "Bongo Platyhelminthes", "Bongo Nematoda", "Bongo Mollusca", "Bongo Porifera", "Bongo Echinodermata",
                "Bongo Chordata");
        List<String> fMan = Arrays.asList("Albert Einstein", "Isaac Newton", "Leonardo da Vinci", "William Shakespeare",
                "Ludwig van Beethoven", "Charles Darwin", "Galileo Galilei", "Winston Churchill",
                "Martin Luther King Jr.", "Mahatma Gandhi", "Nelson Mandela", "Thomas Edison", "Henry Ford",
                "John F. Kennedy", "Michael Jackson", "Elvis Presley", "Pablo Picasso", "Stephen Hawking", "Mark Twain",
                "Vincent van Gogh", "Abraham Lincoln", "George Washington", "Napoleon Bonaparte", "Alexander the Great",
                "Genghis Khan", "Julius Caesar", "Confucius", "Buddha", "Socrates", "Plato", "Aristotle",
                "George Orwell", "Friedrich Nietzsche", "Sigmund Freud", "Carl Jung", "Karl Marx", "Charles Dickens",
                "Ernest Hemingway", "John Steinbeck", "Ray Bradbury", "J.R.R. Tolkien",
                "Stephen King", "George Lucas", "Steven Spielberg", "Alfred Hitchcock", "Orson Welles",
                "Robert De Niro", "Marlon Brando", "Johnny Depp", "Tom Hanks", "Denzel Washington", "Brad Pitt",
                "Leonardo DiCaprio", "Robert Downey Jr.", "Harrison Ford", "Keanu Reeves", "James Dean",
                "Clint Eastwood", "Morgan Freeman", "Samuel L. Jackson", "Jack Nicholson", "Daniel Day-Lewis",
                "Anthony Hopkins", "Al Pacino", "Gene Hackman", "Liam Neeson", "Matthew McConaughey", "Russell Crowe",
                "Ben Affleck", "Matt Damon", "Will Smith", "Jamie Foxx", "John Travolta", "Vin Diesel", "Jason Statham",
                "Hugh Jackman", "Chris Hemsworth", "Chris Evans", "Tom Hardy", "Ryan Reynolds", "Robert Pattinson",
                "Daniel Craig", "Johnny Depp", "Zayn Malik", "Shawn Mendes", "Justin Bieber", "Drake", "Kanye West",
                "Jay-Z", "Ed Sheeran", "Elton John", "Freddie Mercury", "Bruce Springsteen", "Bob Dylan",
                "Stevie Wonder", "Michael Bublé", "Harry Styles", "John Legend", "Marvin Gaye", "David Bowie", "Prince",
                "Ozzy Osbourne", "Adele", "Usher", "Rihanna", "50 Cent", "Lil Wayne", "Eminem", "Snoop Dogg",
                "Post Malone", "Travis Scott", "Tyler, The Creator", "J. Cole", "Kendrick Lamar", "Macklemore",
                "Childish Gambino", "Logic", "Nas", "Rakim", "KRS-One", "Tupac Shakur", "The Notorious B.I.G.", "Big L",
                "MF DOOM", "Mac Miller", "Lil Nas X", "Bad Bunny", "Dr. Dre", "Jimmy Iovine", "Rick Rubin",
                "Jermaine Dupri", "DJ Khaled", "Timbaland", "Pharrell Williams", "Swizz Beatz", "David Guetta",
                "Calvin Harris", "Avicii", "Tiesto", "Deadmau5", "Skrillex", "Marshmello", "Zedd", "Diplo",
                "Steve Aoki", "Hardwell", "Alesso", "Martin Garrix", "Kygo", "Benny Benassi", "Paul van Dyk",
                "Gareth Emery", "Armin van Buuren", "Above & Beyond", "Dimitri Vegas", "Like Mike", "Showtek",
                "Bassnectar", "Ferry Corsten", "Afrojack", "Don Diablo", "Nicky Romero", "Carnage", "Flosstradamus",
                "Yellow Claw", "Kaskade", "R3HAB", "Dillon Francis", "Zeds Dead", "The Chainsmokers", "G-Eazy", "Logic",
                "Lil Uzi Vert", "Lil Pump", "Trippie Redd", "6ix9ine", "Kodak Black", "JAY-Z", "Nas", "Lil Yachty",
                "T-Pain", "R. Kelly", "Chris Brown", "Justin Timberlake", "NSYNC", "Backstreet Boys", "One Direction",
                "BTS", "EXO", "Got7", "SEVENTEEN", "Stray Kids", "NCT", "BLACKPINK", "Red Velvet", "Twice", "GOT7",
                "MONSTA X", "ATEEZ", "Trevor Noah", "Jimmy Fallon", "Stephen Colbert", "David Letterman",
                "Ellen DeGeneres", "Conan O'Brien", "Jimmy Kimmel", "Jon Stewart", "Bill Maher", "David Spade",
                "Chris Rock", "Kevin Hart", "Adam Sandler", "Ben Stiller", "Will Ferrell", "Vince Vaughn", "Seth Rogen",
                "James Franco", "Zach Galifianakis", "Jack Black", "Owen Wilson", "Ben Stiller", "Robin Williams",
                "Jim Carrey", "Steve Carell", "John C. Reilly", "Chris Pratt", "Mark Ruffalo", "Dwayne Johnson",
                "Vin Diesel", "Jason Momoa", "Robert Pattinson", "Henry Cavill", "Tom Holland", "Chris Evans",
                "Chris Hemsworth", "Andrew Garfield", "Michael B. Jordan", "Chadwick Boseman", "Idris Elba",
                "Donnie Yen", "Jet Li", "Tony Jaa", "Scott Adkins", "Mark Hamill", "Peter Dinklage", "Kit Harington",
                "Hugh Grant", "Colin Firth", "Ewan McGregor", "Ben Kingsley", "Daniel Craig", "Gerard Butler",
                "Matt Smith", "Charlie Hunnam", "Michael Fassbender", "Joaquin Phoenix", "Adam Driver", "Oscar Isaac",
                "Joseph Gordon-Levitt", "Nicholas Hoult", "Chris Pine", "Zachary Quinto", "Chris Evans",
                "Tom Hiddleston", "Matthew Fox", "Josh Holloway", "Josh Duhamel", "Hugh Jackman", "David Beckham",
                "Cristiano Ronaldo", "Lionel Messi", "Pele", "Diego Maradona", "Michael Jordan", "LeBron James",
                "Kobe Bryant", "Shaquille O'Neal", "Wayne Gretzky", "Tom Brady", "Roger Federer", "Rafael Nadal",
                "Serena Williams", "Babe Ruth", "Ty Cobb", "Jack Nicklaus", "Tiger Woods", "David Ortiz",
                "Manny Pacquiao", "Floyd Mayweather", "Conor McGregor", "Mike Tyson", "Kareem Abdul-Jabbar",
                "Bill Russell", "Larry Bird", "Magic Johnson", "Kurt Angle", "Steve Austin", "Dwayne Johnson",
                "Brock Lesnar", "John Cena", "Triple H", "Shawn Michaels", "Stone Cold Steve Austin", "Ric Flair",
                "Undertaker", "Randy Orton", "AJ Styles", "Finn Balor", "Seth Rollins", "Roman Reigns", "Becky Lynch",
                "Charlotte Flair", "Sasha Banks", "Bayley", "Nia Jax", "Alexa Bliss", "Rhea Ripley", "Carmella",
                "Naomi", "Asuka", "Shinsuke Nakamura", "Kofi Kingston", "Big E", "Xavier Woods", "Daniel Bryan",
                "Kevin Owens", "Sami Zayn", "Dolph Ziggler", "The Miz", "Rusev", "Cesaro", "AJ Styles", "Bobby Roode",
                "Drew McIntyre", "Sheamus", "Finn Balor", "Baron Corbin", "Lio Rush", "Johnny Gargano",
                "Tommaso Ciampa", "Aleister Black", "Adam Cole", "Velveteen Dream", "Keith Lee", "Karrion Kross",
                "Bronson Reed", "Roderick Strong", "Moustache Mountain", "Trent Seven", "Tyler Bate", "Toni Storm",
                "Piper Niven", "Rhea Ripley", "Raquel González", "Dakota Kai", "Ember Moon", "Io Shirai", "Kairi Sane",
                "Mia Yim", "Shayna Baszler", "Jessamyn Duke", "Marina Shafir", "Lacey Evans", "Mandy Rose",
                "Sonya Deville", "Billie Kay", "Peyton Royce", "Toni Storm", "Becky Lynch", "Sasha Banks",
                "Charlotte Flair", "Nia Jax", "Asuka", "Kairi Sane", "Shayna Baszler", "Io Shirai", "Rhea Ripley",
                "Candice LeRae", "Tegan Nox", "Mia Yim", "Dakota Kai", "Ember Moon", "Lacey Evans", "Sarah Logan",
                "Liv Morgan", "Ruby Riott", "Nikki Cross", "Toni Storm", "Piper Niven", "Rhea Ripley", "Dakota Kai",
                "Lacey Evans", "Asuka", "Alexa Bliss", "Charlotte Flair", "Becky Lynch", "Sasha Banks", "Nia Jax",
                "Kairi Sane", "Io Shirai", "Ember Moon");
        List<String> fWomen = Arrays.asList("Marie Curie", "Oprah Winfrey", "Malala Yousafzai", "Ruth Bader Ginsburg",
                "Margaret Thatcher", "Amelia Earhart", "Frida Kahlo", "Harriet Tubman", "Jane Goodall", "Mother Teresa",
                "Simone de Beauvoir", "Maya Angelou", "Indira Gandhi", "Angela Merkel", "Michelle Obama", "Beyoncé",
                "Rihanna", "Taylor Swift", "Lady Gaga", "Adele", "Helen Keller", "Anne Frank",
                "Virginia Woolf", "Chimamanda Ngozi Adichie", "Tina Fey", "Eleanor Roosevelt", "Billie Holiday",
                "Marilyn Monroe", "Whitney Houston", "Diana Ross", "Janis Joplin", "Lucille Ball", "Coco Chanel",
                "Bette Davis", "Audrey Hepburn", "Meryl Streep", "Dame Judi Dench", "Gloria Steinem",
                "Catherine the Great", "Cleopatra", "Queen Elizabeth I", "Empress Dowager Cixi", "Marie Antoinette",
                "Princess Diana", "Elizabeth Taylor", "Julia Child", "Michelle Pfeiffer", "Natalie Portman",
                "Nicole Kidman", "Scarlett Johansson", "Angelina Jolie", "Jessica Chastain", "Emma Watson",
                "Brie Larson", "Gal Gadot", "Viola Davis", "Lupita Nyong'o", "Kate Winslet", "Cate Blanchett",
                "Halle Berry", "Rosamund Pike", "Jennifer Lawrence", "Saoirse Ronan", "Amy Adams", "Drew Barrymore",
                "Reese Witherspoon", "Jessica Alba", "Eva Longoria", "Vanessa Hudgens", "Mandy Moore", "Selena Gomez",
                "Gwen Stefani", "Shakira", "Christina Aguilera", "Janet Jackson", "Britney Spears", "Demi Lovato",
                "Ariana Grande", "Miley Cyrus", "Halsey", "Katy Perry", "Sia", "Janelle Monáe", "Billie Eilish",
                "Camila Cabello", "Dua Lipa", "Nicki Minaj", "Cardi B", "Lizzo", "Doja Cat", "Bebe Rexha",
                "Megan Thee Stallion", "Nicki Minaj", "Rosario Dawson", "Taraji P. Henson", "Octavia Spencer",
                "Angela Bassett", "Michelle Yeoh", "Connie Britton", "Chandra Wilson", "Viola Davis",
                "Patricia Clarkson", "Mary J. Blige", "Cynthia Erivo", "Sofia Vergara", "Selma Hayek", "Penélope Cruz",
                "Maggie Smith", "Laura Linney", "Jodie Foster", "Kristen Stewart", "Naomi Watts", "Tilda Swinton",
                "Gina Rodriguez", "Maya Rudolph", "Reba McEntire", "Sheryl Crow", "Alanis Morissette", "Lauryn Hill",
                "Kacey Musgraves", "Miranda Lambert", "Shania Twain", "Nina Simone", "Joni Mitchell", "Diana Krall",
                "Patti Smith", "Tori Amos", "Sandy Denny", "Björk", "Fiona Apple", "Nikki Sixx", "Hayley Williams",
                "Amy Lee", "Karen O", "Debbie Harry", "Siouxsie Sioux", "Kate Bush", "Sade", "Annie Lennox",
                "Alicia Keys", "Macy Gray", "Norah Jones", "Marina and the Diamonds", "Lana Del Rey", "Tinashe",
                "Charli XCX", "Renee Zellweger", "Emma Stone", "Kristen Wiig", "Maya Rudolph", "Tina Turner",
                "Anjelica Huston", "Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Drew Barrymore", "Kate Hudson",
                "Goldie Hawn", "Mary Steenburgen", "Jenna Fischer", "Angela Kinsey", "Mindy Kaling", "Tessa Thompson",
                "Tiffany Haddish", "Kristen Bell", "Rachel McAdams", "Dakota Johnson", "Lucy Liu", "Jessica Biel",
                "Kristen Dunst", "Margot Robbie", "Elizabeth Banks", "Lily Collins", "Chloe Grace Moretz",
                "Emma Roberts", "Kiernan Shipka", "Millie Bobby Brown", "Sophia Turner", "Maisie Williams",
                "Nathalie Emmanuel", "Jessica Henwick", "Gemma Chan", "Jessica Brown Findlay", "Emilia Clarke",
                "Kate Mara", "Kelly Marie Tran", "Rosario Dawson", "Kate Bosworth", "Dianna Agron", "Vanessa Kirby",
                "Greta Gerwig", "Alicia Vikander", "Scarlett Johannson", "Mary Elizabeth Winstead", "Catherine O'Hara",
                "Tracee Ellis Ross", "Wanda Sykes", "Kerry Washington", "Viola Davis", "Laverne Cox", "Nia Long",
                "Ava DuVernay", "Shonda Rhimes", "Issa Rae", "Lena Waithe", "Mindy Kaling", "Rashida Jones",
                "Yara Shahidi", "Awkwafina", "Constance Wu", "Renee Elise Goldsberry", "Auli'i Cravalho",
                "Kaitlyn Dever", "Maya Hawke", "Sydney Sweeney", "Olivia Rodrigo", "Madelaine Petsch", "Cole Sprouse",
                "KJ Apa", "Camila Mendes", "Lili Reinhart", "Sophie Turner", "Maisie Williams", "Sarah Gadon",
                "Hannah John-Kamen", "Kaya Scodelario", "Daisy Ridley", "Carrie Fisher", "Adele Exarchopoulos",
                "Léa Seydoux", "Cécile de France", "Tahar Rahim", "Charlotte Gainsbourg", "Juliette Binoche",
                "Isabelle Huppert", "Sophie Marceau", "Marion Cotillard", "Ana de Armas", "Mélanie Laurent", "Paz Vega",
                "Penélope Cruz", "Salma Hayek", "Rosario Dawson", "Halle Berry", "Gina Torres", "Sofia Vergara",
                "Vanessa Williams", "Tracee Ellis Ross", "Angela Bassett", "Alfre Woodard", "Lynn Whitfield",
                "Phylicia Rashad", "Misty Copeland", "Michelle Obama", "Kamala Harris", "Tulsi Gabbard", "Sarah Palin",
                "Elizabeth Warren", "Condoleezza Rice", "Hillary Clinton", "Nancy Pelosi", "Cory Booker",
                "Stacey Abrams", "Tammy Baldwin", "Kirsten Gillibrand", "Catherine Cortez Masto", "Janet Napolitano",
                "Debbie Wasserman Schultz", "Nikki Haley", "Dianne Feinstein", "Patty Murray", "Maria Cantwell",
                "Amy Klobuchar", "Tammy Duckworth", "Elizabeth Warren", "Marsha Blackburn", "Joni Ernst",
                "Cynthia Nixon", "Barbara Lee", "Katie Porter", "Ilhan Omar", "Ayanna Pressley",
                "Alexandria Ocasio-Cortez", "Tulsi Gabbard", "Kristen Sinema", "Maggie Hassan", "Hillary Clinton",
                "Condoleezza Rice", "Madeleine Albright", "Susan Rice", "Katherine Johnson", "Mae Jemison",
                "Jessica Ennis-Hill", "Michelle Kwan", "Serena Williams", "Venus Williams", "Diana Taurasi",
                "Danica Patrick", "Misty Copeland", "Mary Barra", "Ginni Rometty", "Sheryl Sandberg", "Indra Nooyi",
                "Ursula Burns", "Melinda Gates", "Anne Wojcicki", "Barbara Corcoran", "Oprah Winfrey",
                "Diane von Furstenberg", "Zaha Hadid", "Marissa Mayer", "Reshma Saujani", "Robin Chase", "Ada Lovelace",
                "Hedy Lamarr", "Katherine Johnson", "Judy Blume", "Marissa Meyer", "Anne Frank", "Ruth Bader Ginsburg",
                "Michelle Obama", "Hillary Clinton", "Malala Yousafzai", "Amelia Earhart", "Marie Curie",
                "Eleanor Roosevelt", "Simone de Beauvoir", "Frida Kahlo", "Virginia Woolf", "Harriet Tubman",
                "Margaret Atwood", "Margaret Thatcher", "Sonia Sotomayor", "Rosa Parks", "Mother Teresa", "Bette Davis",
                "Jessica Lange", "Meryl Streep", "Catherine Deneuve", "Kate Winslet", "Holly Hunter", "Jodie Foster",
                "Emma Thompson", "Sharon Stone", "Michelle Yeoh", "Susan Sarandon", "Beyoncé", "Adele", "Rihanna",
                "Taylor Swift", "Lady Gaga", "Nicki Minaj", "Lizzo", "Megan Thee Stallion", "Ariana Grande",
                "Demi Lovato", "Camila Cabello", "Selena Gomez", "Shakira", "Katy Perry", "Billie Eilish", "Halsey",
                "Miley Cyrus", "Demi Moore", "Angelina Jolie", "Charlize Theron",
                "Natalie Portman", "Scarlett Johansson", "Jessica Chastain", "Emily Blunt", "Chloe Grace Moretz",
                "Dakota Johnson", "Sophie Turner", "Maisie Williams", "Emma Watson", "Kristen Stewart", "Zendaya",
                "Lupita Nyong'o", "Viola Davis", "Taraji P. Henson", "Angela Bassett", "Maya Rudolph",
                "Tracee Ellis Ross", "Mindy Kaling", "Constance Wu", "Michelle Rodriguez", "Gina Rodriguez",
                "Ava DuVernay", "Issa Rae", "Kerry Washington", "Halle Berry", "Nia Long", "Viola Davis",
                "Gabrielle Union", "Ayesha Curry", "Rachel Lindsay", "Kristin Chenoweth", "Lea Michele", "Mandy Moore",
                "Anne Hathaway", "Kate Hudson", "Goldie Hawn", "Mary Steenburgen", "Sandra Bullock", "Jennifer Lopez",
                "Drew Barrymore", "Lindsay Lohan", "Kristen Bell", "Rachel McAdams", "Emma Stone", "Margot Robbie",
                "Alison Brie", "Anne Hathaway", "Mila Kunis", "Natalie Dormer", "Katherine Langford",
                "Madelaine Petsch", "Vanessa Morgan", "Sabrina Carpenter", "Kiernan Shipka", "Lily Collins",
                "Emma Roberts", "Maisie Williams", "Lena Dunham", "Amy Schumer", "Tiffany Haddish", "Jessica Williams",
                "Rebel Wilson", "Kristen Wiig", "Anna Kendrick", "Maya Rudolph", "Selena Gomez", "Demi Lovato",
                "Bebe Rexha", "Camila Cabello", "Tinashe", "Rihanna", "Nicki Minaj", "Miley Cyrus", "Billie Eilish",
                "Halsey", "Sabrina Carpenter", "Ariana Grande", "Katy Perry", "Taylor Swift", "Lorde", "Dua Lipa",
                "Olivia Rodrigo", "Gwen Stefani", "Shakira", "Alanis Morissette", "Tori Amos", "Annie Lennox", "Sade",
                "Norah Jones", "Sara Bareilles", "Mandy Moore", "Hilary Duff", "Jessica Simpson", "Carrie Underwood",
                "Reba McEntire", "Sheryl Crow", "Miranda Lambert", "Kacey Musgraves", "Dolly Parton", "Janet Jackson",
                "Mariah Carey", "Whitney Houston", "Celine Dion", "Aretha Franklin", "Billie Holiday",
                "Ella Fitzgerald", "Nina Simone", "Diana Ross", "Patti LaBelle", "Gladys Knight", "Janelle Monáe",
                "SZA", "Solange Knowles", "Keri Hilson", "Tamia", "Angie Stone", "Jill Scott", "Erykah Badu",
                "Musiq Soulchild", "Lalah Hathaway", "India.Arie", "Kacey Musgraves", "Miranda Lambert",
                "Carrie Underwood", "Ashley Monroe", "Kacey Musgraves", "RaeLynn", "Taylor Swift", "Demi Lovato",
                "Ariana Grande", "Bebe Rexha", "Selena Gomez", "Camila Cabello", "Halsey", "Billie Eilish",
                "Charli XCX", "Miley Cyrus", "Katy Perry", "Megan Thee Stallion", "Doja Cat", "Nicki Minaj", "Rihanna",
                "Lady Gaga", "Adele", "Shakira", "Alicia Keys", "Mary J. Blige", "Toni Braxton", "Janet Jackson",
                "Beyoncé", "Demi Lovato", "Brandy", "Mya", "Ashanti", "Keyshia Cole", "Eve", "Missy Elliott",
                "Lil' Kim", "Trina", "Nicki Minaj", "Cardi B", "Saweetie", "Doja Cat", "City Girls",
                "Megan Thee Stallion", "Rico Nasty", "Tierra Whack", "Cupcakke", "Janelle Monáe", "Andra Day",
                "Corinne Bailey Rae", "Macy Gray", "Lianne La Havas", "H.E.R.", "Summer Walker", "Jhené Aiko",
                "Sabrina Claudio", "Ella Mai", "SZA", "Tinashe", "Chloe x Halle", "Mimi Webb", "Tori Kelly",
                "Olivia Rodrigo", "Kacey Musgraves", "Bebe Rexha", "Rita Ora", "Charli XCX", "Dua Lipa",
                "Sabrina Carpenter", "Carly Rae Jepsen", "Jessie J", "Meghan Trainor", "Zara Larsson",
                "Hailee Steinfeld", "Charlie Puth", "Bruno Mars", "Ed Sheeran", "Shawn Mendes", "Sam Smith",
                "James Arthur", "John Legend", "Justin Bieber", "The Weeknd", "Khalid", "Hozier", "Charlie Puth",
                "Justin Timberlake", "Adam Levine", "Drake", "J. Cole", "Kendrick Lamar", "Lil Wayne", "50 Cent",
                "Eminem", "Snoop Dogg", "Ice Cube", "Macklemore", "Chance the Rapper", "Tyler, The Creator", "Logic",
                "Lil Nas X", "Kanye West", "Post Malone", "Kacey Musgraves", "Halsey", "Lana Del Rey", "Ariana Grande",
                "Demi Lovato", "Selena Gomez", "Billie Eilish", "Dua Lipa", "Olivia Rodrigo", "Miley Cyrus",
                "Katy Perry", "Rihanna", "Beyoncé", "Lady Gaga", "Shakira", "Madonna", "Taylor Swift",
                "Alanis Morissette", "Nina Simone", "Etta James", "Ella Fitzgerald", "Diana Ross", "Mary J. Blige",
                "Whitney Houston", "Adele", "Brandy", "Mya", "Ashanti", "Keyshia Cole", "Lil' Kim", "Missy Elliott",
                "Cardi B", "Nicki Minaj", "Doja Cat", "Megan Thee Stallion", "Saweetie", "Rico Nasty", "Tierra Whack",
                "Coco Jones", "Tinashe", "Summer Walker", "Sabrina Claudio", "Ella Mai", "H.E.R.", "Jhené Aiko",
                "Ari Lennox", "K. Michelle", "Yuna", "Andra Day", "Brittany Howard", "Corinne Bailey Rae",
                "Lianne La Havas", "Janelle Monáe", "Solange Knowles", "Nina Sky", "Hayley Kiyoko", "Bebe Rexha",
                "Tori Kelly", "Jessie J", "Carly Rae Jepsen", "Meghan Trainor", "Zara Larsson", "Charli XCX",
                "Sabrina Carpenter", "Rachel Platten", "Julia Michaels", "Olivia Rodrigo", "Madison Beer", "Tate McRae",
                "GAYLE", "Mimi Webb", "Tinashe", "Megan Thee Stallion", "Doja Cat", "Saweetie", "Cardi B",
                "Nicki Minaj", "Rihanna", "Beyoncé", "Ariana Grande", "Demi Lovato", "Selena Gomez", "Halsey",
                "Billie Eilish", "Miley Cyrus", "Katy Perry", "Dua Lipa", "Olivia Rodrigo", "Adele", "Taylor Swift",
                "Megan Thee Stallion", "Carly Rae Jepsen", "Madison Beer", "GAYLE", "Coco Jones", "Hayley Kiyoko",
                "Ella Mai", "SZA", "Ari Lennox", "Summer Walker", "Sabrina Claudio", "H.E.R.", "Jhené Aiko",
                "Andra Day", "Corinne Bailey Rae", "Lianne La Havas", "Janelle Monáe", "Solange Knowles", "Nina Sky",
                "Kacey Musgraves", "Miranda Lambert", "Carrie Underwood", "Reba McEntire", "Sheryl Crow",
                "Mary J. Blige", "Nicki Minaj", "Lil' Kim", "Missy Elliott", "Cardi B", "Doja Cat", "Saweetie",
                "Rico Nasty", "Tierra Whack", "Megan Thee Stallion", "Demi Lovato", "Ariana Grande", "Selena Gomez",
                "Billie Eilish", "Katy Perry", "Miley Cyrus", "Halsey", "Charli XCX", "Rihanna", "Lady Gaga", "Beyoncé",
                "Tina Turner", "Whitney Houston", "Celine Dion", "Mariah Carey", "Diana Ross", "Etta James",
                "Aretha Franklin", "Nina Simone", "Alanis Morissette", "Fiona Apple", "Norah Jones", "Joni Mitchell",
                "Sade", "Tori Amos", "Annie Lennox", "Kacey Musgraves", "Miranda Lambert", "Carrie Underwood",
                "Reba McEntire", "Sheryl Crow", "Miley Cyrus", "Ariana Grande", "Selena Gomez", "Katy Perry",
                "Billie Eilish");
        List<String> networkingTerms = Arrays.asList("TCP", "IP", "HTTP", "HTTPS", "FTP", "SFTP", "SMTP", "DNS", "DHCP",
                "ARP", "MAC", "Ethernet", "LAN", "WAN", "MAN", "PAN", "VPN", "NAT", "CIDR", "Subnet", "Router",
                "Switch", "Hub", "Gateway", "Firewall", "Proxy", "Load Balancer", "Access Point", "Bridge", "Modem",
                "Repeater", "Network Topology", "Bus", "Ring", "Star", "Mesh", "Protocol", "Packet", "Frame",
                "IP Address", "IPv4", "IPv6", "Broadcast", "Unicast", "Multicast", "Anycast", "Loopback", "Ping",
                "Traceroute", "ICMP", "TTL", "Port", "Socket", "Bandwidth", "Latency", "Throughput", "Jitter", "QoS",
                "MTU", "DNS Resolver", "Domain", "URL", "Hostname", "SSID", "BSSID", "VLAN", "ARP Cache", "RARP",
                "IGMP", "BGP", "OSPF", "EIGRP", "RIP", "CSMA/CD", "CSMA/CA", "Token Ring", "WEP", "WPA", "WPA2", "WPA3",
                "SSID", "BSSID", "AP Isolation", "DMZ", "WLAN", "Channel", "Collision Domain", "Broadcast Domain",
                "Segment", "Fiber Optic", "Coaxial", "Twisted Pair", "Cat5", "Cat5e", "Cat6", "Cat6a", "PoE", "PLC",
                "SNMP", "Syslog", "NetFlow", "sFlow", "TFTP", "Traceroute", "NetBIOS", "Socket API",
                "Application Layer", "Presentation Layer", "Session Layer", "Transport Layer", "Network Layer",
                "Data Link Layer", "Physical Layer", "OSI Model", "TCP/IP Model", "Encapsulation", "Decapsulation",
                "Port Forwarding", "Virtual IP", "Multihoming", "Broadcast Storm", "DNS Spoofing", "ARP Spoofing",
                "MAC Flooding", "DHCP Snooping", "IP Spoofing", "Network Security", "Penetration Testing", "IDS", "IPS",
                "Zero Trust", "Firewalls", "Intrusion Detection", "Intrusion Prevention", "Network ACL", "DMVPN",
                "Network ACL", "SSL", "TLS", "Handshaking", "Digital Certificate", "CA", "Packet Sniffing",
                "Packet Filtering", "Load Sharing", "Policy Routing", "Loop Prevention", "Link Aggregation",
                "Redundancy", "Failover", "High Availability", "Latency Optimization", "Congestion Control",
                "Network Interface", "NIC", "Wireless NIC", "Ping of Death", "Botnet", "DDoS", "SYN Flood",
                "Port Scanning", "Brute Force Attack", "Dictionary Attack", "Man in the Middle", "Eavesdropping",
                "Session Hijacking", "Spoofing Attack", "Traffic Analysis", "Backdoor", "Trojan Horse", "Worm", "Virus",
                "Malware", "Spyware", "Phishing", "Social Engineering", "DNS Hijacking", "SSL Hijacking",
                "SSL/TLS Certificate", "Decryption", "Cipher", "AES", "RSA", "Elliptic Curve", "Hashing", "MD5",
                "SHA-1", "SHA-256", "Firewall Rule", "Firewall Policy", "Content Filtering", "Deep Packet Inspection",
                "VPN Tunneling", "L2TP", "PPTP", "IPSec", "SSL VPN", "GRE Tunnel", "Split Tunneling", "SSH Tunnel",
                "Site-to-Site VPN", "Remote Access VPN", "Point-to-Point", "Multi-Protocol", "Carrier Ethernet", "MPLS",
                "SD-WAN", "NFV", "SDN", "Data Plane", "Control Plane", "Forwarding Plane", "Edge Computing",
                "Fog Computing", "Cloud Computing", "ISP", "Data Center", "Server Farm", "Load Distribution", "Cluster",
                "Data Storage", "SAN", "NAS", "RAID", "Backup", "Disaster Recovery", "Business Continuity",
                "Elasticity", "Scalability", "Redundancy", "Replication", "Failback", "DRaaS", "Cloud Backup",
                "Hybrid Cloud", "Public Cloud", "Private Cloud", "Microservices", "Containerization", "Kubernetes",
                "Docker", "IPv4 Header", "IPv6 Header", "TCP Header", "UDP Header", "HTTP Header", "Encapsulation",
                "Decapsulation", "Subnet Mask", "Broadcast Address", "Default Gateway", "Route", "Routing Table",
                "Dynamic Routing",
                "Static Routing", "CIDR Notation", "Supernetting", "Fragmentation", "Reassembly", "TCP Window",
                "Sliding Window", "Three-Way Handshake", "FIN", "SYN", "ACK", "RST", "Flow Control",
                "Congestion Control", "Network Monitoring", "Network Analysis", "Wireshark", "Traceroute", "Ping Sweep",
                "Bandwidth Testing", "Latency Testing", "Traceroute Tool", "Remote Desktop", "VNC", "RDP", "Telnet",
                "SSH", "NTP", "Time Server", "Multihop", "Hop Count", "TTL", "Round Trip Time", "Bottleneck",
                "Throughput", "Downlink", "Uplink", "Router OS", "Edge Router", "Core Router", "Access Router",
                "WAN Router", "LAN Router", "Firewall Appliance", "Security Appliance", "Switching Hub", "Smart Switch",
                "Managed Switch", "Unmanaged Switch", "Load Balancing", "Failover Cluster", "Redundant Link",
                "Hot Standby", "Cold Standby", "Session Persistence", "Packet Queue", "Buffer Overflow", "Bitrate",
                "Network Latency", "Download Speed", "Upload Speed", "ISP Throttling", "Bandwidth Cap",
                "Mobile Network", "Cell Tower", "5G", "4G", "3G", "Edge Network", "Backhaul", "Fiber Optics", "DSL",
                "Cable Modem", "Wireless Router", "Hotspot", "Mesh Network", "Ad-Hoc Network", "Peer-to-Peer",
                "Client-Server", "Bandwidth Allocation");
        List<String> tech = Arrays.asList("Artificial Intelligence", "Machine Learning", "Deep Learning", "Blockchain",
                "Cryptocurrency", "Big Data", "Cloud Computing", "Internet of Things", "Augmented Reality",
                "Virtual Reality", "5G", "Edge Computing", "Quantum Computing", "Cybersecurity", "DevOps",
                "Robotic Process Automation", "Natural Language Processing", "Data Science", "Software Development",
                "Web Development", "Mobile Development", "Microservices", "API", "SaaS", "PaaS", "IaaS",
                "Virtualization", "Containerization", "Kubernetes", "Docker", "Serverless Computing",
                "Agile Development", "Scrum", "Kanban", "Continuous Integration", "Continuous Deployment",
                "Data Analytics", "Business Intelligence", "User Experience", "User Interface", "Design Thinking",
                "Responsive Design", "Progressive Web Apps", "Mobile Apps", "Desktop Apps", "Hybrid Apps",
                "Cross-Platform Development", "Code Review", "Version Control", "Git", "GitHub", "Bitbucket", "GitLab",
                "Continuous Monitoring", "Load Balancing", "Caching", "Database Management", "SQL", "NoSQL", "GraphQL",
                "RESTful APIs", "Microservices Architecture", "Monolithic Architecture", "Data Warehousing",
                "Data Lakes", "Data Mining", "Data Visualization", "Predictive Analytics", "Descriptive Analytics",
                "Prescriptive Analytics", "Machine Vision", "Speech Recognition", "Facial Recognition",
                "Image Processing", "Augmented Analytics", "Robotics", "Drone Technology", "Wearable Technology",
                "Smart Home Technology", "Smart Cities", "Smart Manufacturing", "IoT Devices", "Health Tech", "Fintech",
                "EdTech", "AgriTech", "BioTech", "CleanTech", "Quantum Cryptography", "Neural Networks", "Fuzzy Logic",
                "Expert Systems", "Chatbots", "Digital Twins", "Remote Sensing", "3D Printing",
                "Additive Manufacturing", "Nanotechnology", "Biometrics", "Geolocation", "Location-Based Services",
                "E-commerce", "Digital Marketing", "SEO", "SEM", "Social Media Marketing", "Content Marketing",
                "Affiliate Marketing", "Email Marketing", "Marketing Automation", "Customer Relationship Management",
                "Enterprise Resource Planning", "Supply Chain Management", "Project Management Tools",
                "Collaboration Tools", "Productivity Tools", "Remote Work Technology", "Telecommuting Tools",
                "Video Conferencing", "Webinars", "Online Learning Platforms", "Virtual Events", "Cloud Storage",
                "Data Backup", "Disaster Recovery", "Internet Security", "Network Security", "Endpoint Security",
                "Application Security", "Threat Intelligence", "Intrusion Detection", "Firewall", "Encryption",
                "Tokenization", "Access Control", "Identity Management", "Single Sign-On",
                "Multi-Factor Authentication", "Privacy Technology", "Data Governance", "Compliance Technology",
                "Risk Management", "Blockchain Technology", "Smart Contracts", "Initial Coin Offerings",
                "Decentralized Finance", "NFTs", "Digital Wallets", "Payment Gateways", "Point of Sale Systems",
                "Retail Technology", "Logistics Technology", "Fleet Management", "Telematics",
                "Health Information Technology", "Electronic Health Records", "Telehealth", "Genomic Technology",
                "Pharmaceutical Technology", "Clinical Trials Technology", "Artificial Organs",
                "Prosthetics Technology", "Bioinformatics", "Computational Biology", "E-Learning Technology",
                "Learning Management Systems", "Massive Open Online Courses", "Digital Content Creation",
                "Streaming Technology", "Content Delivery Networks", "Digital Rights Management",
                "Intellectual Property Technology", "Copyright Management", "Media Technology", "Television Technology",
                "Radio Technology", "Film Technology", "Video Game Technology", "Game Development",
                "Virtual Reality Gaming", "Augmented Reality Gaming", "Mobile Gaming", "Esports Technology",
                "Gaming Hardware",
                "Graphics Processing", "Game Engines", "Artificial Intelligence in Gaming", "Cloud Gaming",
                "Interactive Media", "Transmedia Storytelling", "User-Generated Content", "Open Source Technology",
                "Crowdsourcing", "Crowdfunding", "Innovation Technology", "Research and Development Technology",
                "Technology Transfer", "Public Key Infrastructure", "Secure Sockets Layer", "Transport Layer Security",
                "Blockchain Security", "Internet of Medical Things", "Smart Grids", "Electric Vehicles",
                "Autonomous Vehicles", "Connected Vehicles", "Ride-Sharing Technology", "Mobility as a Service",
                "Smart Transportation", "Travel Technology", "Tourism Technology", "Hospitality Technology",
                "Smart Agriculture", "Precision Farming", "Agricultural Drones", "Hydroponics Technology",
                "Aquaponics Technology", "Vertical Farming", "Food Technology", "Nutrition Technology",
                "Sustainable Technology", "Renewable Energy Technology", "Solar Energy Technology",
                "Wind Energy Technology", "Battery Technology", "Energy Storage Technology", "Smart Metering",
                "Home Automation", "Personal Assistants", "Voice Recognition", "Smart Wearables", "Fitness Trackers",
                "Smart Watches", "Smart Glasses", "Health Monitoring Devices", "Telecommunication Technology",
                "Networking Technology", "Wireless Technology", "Bluetooth Technology", "Wi-Fi Technology",
                "Satellite Technology", "Optical Fiber Technology", "Broadcast Technology",
                "Data Transmission Technology", "Information Theory", "Signal Processing", "Control Systems",
                "Feedback Systems", "System Dynamics", "Digital Signal Processing", "Analog Technology", "Electronics",
                "Microcontrollers", "Embedded Systems", "Circuit Design", "Semiconductor Technology",
                "Materials Science", "Nanomaterials", "Smart Materials", "Biodegradable Materials",
                "Recyclable Materials", "3D Modeling Technology", "Computer-Aided Design",
                "Computer-Aided Manufacturing", "Simulation Technology", "Virtual Prototyping", "Sustainable Design",
                "Green Technology", "Clean Energy Technology", "Waste Management Technology",
                "Water Treatment Technology", "Air Quality Technology", "Environmental Monitoring Technology",
                "Ecological Technology", "Climate Technology", "Geothermal Technology", "Biomass Technology",
                "Hydrogen Technology", "Carbon Capture Technology", "Climate Resilience Technology",
                "Disaster Recovery Technology", "Emergency Management Technology", "Public Safety Technology",
                "Smart Security", "Surveillance Technology", "Access Control Technology", "Safety Technology",
                "Transportation Safety Technology", "Industrial Automation", "Industrial Internet of Things",
                "Smart Factories", "Manufacturing Technology", "Supply Chain Technology", "Retail Automation",
                "Digital Supply Chain", "Inventory Management Technology", "Logistics Automation",
                "Warehouse Automation", "Smart Logistics", "Last Mile Delivery Technology",
                "Blockchain in Supply Chain", "Artificial Intelligence in Supply Chain", "Technology in Agriculture",
                "Food Safety Technology", "Quality Control Technology", "Technology in Construction",
                "Building Information Modeling", "Smart Buildings", "Sustainable Construction Technology",
                "Green Building Technology", "Technology in Education", "EdTech Innovations",
                "Online Assessment Technology", "Learning Analytics", "Adaptive Learning Technology",
                "Interactive Learning Technology", "Distance Learning Technology");

        List<String> allOptions = new ArrayList<>();
        allOptions.addAll(birds);
        allOptions.addAll(animals);
        allOptions.addAll(fMan);
        allOptions.addAll(fWomen);
        allOptions.addAll(tech);
        allOptions.addAll(networkingTerms);
        Collections.shuffle(allOptions);

        List<Double> t = Arrays.asList(5.0,5.5,6.0,6.5,7.0,8.0,8.6,9.3,9.5,9.7);
        Robot robot = new Robot();

        for (int i = 0; i < 120; i++) {
            String text = allOptions.get(i % allOptions.size());
            double sleepTime = t.get(ThreadLocalRandom.current().nextInt(t.size())) * 1000;

            pressKey(robot, KeyEvent.VK_ENTER);
            typeText(robot, "   ");
            typeText(robot, text);
            pressKey(robot, KeyEvent.VK_ENTER);
            pressKey(robot, KeyEvent.VK_ENTER);

            Thread.sleep((long) sleepTime);
        }
    }

    private static void typeText(Robot robot, String text) {
        for (char c : text.toCharArray()) {
            int keyCode = KeyEvent.getExtendedKeyCodeForChar(c);
            if (KeyEvent.CHAR_UNDEFINED == keyCode) {
                continue;
            }
            robot.keyPress(keyCode);
            robot.keyRelease(keyCode);
        }
    }

    private static void pressKey(Robot robot, int keyCode) {
        robot.keyPress(keyCode);
        robot.keyRelease(keyCode);
    }
}
